apiVersion: mikrotik.network-operator.margays.dev/v1alpha1
kind: Device
metadata:
  labels:
    app.kubernetes.io/name: network-operator
    app.kubernetes.io/managed-by: kustomize
  name: device-sample
spec:
  # TODO(user): Add fields here
